global:
  storageClass: glass-cfg
  imagePullSecrets:
    - regcred
image:
  registry: docker.io
  repository: bitnami/redis
  tag: latest
  digest: sha256:061a40d93f0deb5f390866b0800f96a58dea8adde319af872523f1038b4a3a2b
auth:
  existingSecret: "auth-redis"
  existingSecretPasswordKey: "redis-password"
  usePasswordFiles: true
master:
  persistence:
    accessModes: ["ReadWriteMany"]
replica:
  persistence:
    accessModes: ["ReadWriteMany"]
sentinel:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/redis-sentinel
    tag: latest
    digest: sha256:227cd52aae97a987a5cee995027720dab7ba1f16c554340ad905b497dbe537d9
  masterSet: authelia
  persistence:
    accessModes: ["ReadWriteMany"]
networkPolicy:
  enabled: true
  ingressNSPodMatchLabels:
    app.kubernetes.io/name: authelia
metrics:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/redis-exporter
    tag: latest
    digest: sha256:fd5a0c9d1c7c316bd928d5837a54edc47176178023d6f976b83cd1341c4f8931
volumePermissions:
  enabled: true
  image:
    registry: docker.io
    repository: bitnami/os-shell
    tag: latest
    digest: sha256:475531b83cc9e79b0bacbb7b899f949e634490ec88267e6803184f8f2d54a549
