global:
  storageClass: glass-cfg
  imagePullSecrets:
    - regcred
image:
  repository: bitnamilegacy/redis
  tag: 8.2.1-debian-12-r0
auth:
  existingSecret: "auth-redis"
  existingSecretPasswordKey: "redis-password"
  usePasswordFiles: true
master:
  podSecurityContext:
    fsGroup: 65532
  containerSecurityContext:
    runAsUser: 65532
  persistence:
    accessModes: ["ReadWriteMany"]
replica:
  podSecurityContext:
    fsGroup: 65532
  containerSecurityContext:
    runAsUser: 65532
  persistence:
    accessModes: ["ReadWriteMany"]
sentinel:
  enabled: true
  image:
    repository: bitnamilegacy/redis-sentinel
    tag: 8.2.1-debian-12-r0
  masterSet: authelia
  podSecurityContext:
    fsGroup: 65532
  containerSecurityContext:
    runAsUser: 65532
  persistence:
    accessModes: ["ReadWriteMany"]
networkPolicy:
  enabled: true
  ingressNSPodMatchLabels:
    app.kubernetes.io/name: authelia
metrics:
  enabled: true
  image:
    repository: bitnamilegacy/redis-exporter
    tag: 1.76.0-debian-12-r0
  containerSecurityContext:
    runAsUser: 65532
volumePermissions:
  enabled: true
  image:
    repository: bitnamilegacy/os-shell
    tag: 12-debian-12-r51
