apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubi8-deployment
  labels:
    app: ubi8
spec:
  replicas: 3
  strategy: 
    type: RollingUpdate
  selector:
    matchLabels:
      app: ubi8
  template:
    metadata:
      labels:
        app: ubi8
    spec:
      containers:
      - name: ubi8
        image: ubi8
        imagePullPolicy: IfNotPresent
        
        command: ['sh', '-c', 'echo Container 1 is Running ; sleep 3600']
