
- name: Add MetalLB Chart Repo
  kubernetes.core.helm_repository:
    name: metallb
    repo_url: https://metallb.github.io/metallb

- name: Deploy Latest MetalLB
  kubernetes.core.helm:
    name: metallb
    chart_ref: metallb/metallb
    release_namespace: metallb
    create_namespace: true

# - name: Deploy MetalLB Resources
#   kubernetes.core.k8s:
#     state: present
#     src: files/kubernetes/values/networking/metallb-resources.yaml

# TODO
# kubectl edit ns/metallb
# # add the following labels
# #  labels:
# #    pod-security.kubernetes.io/enforce: privileged
# #    pod-security.kubernetes.io/audit: privileged
# #    pod-security.kubernetes.io/warn: privileged

# > ## PASS/FAIL: LoadBalancer External IP
# > Install nginx with an external IP
# > - `kubectl apply -f infrastructure/test-nginx.yaml`
# > - `watch kubectl get svc -n default`

