---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: windowpane
  namespace: public
  labels:
    app.kubernetes.io/name: windowpane
    app.kubernetes.io/part-of: windowpane
    app.kubernetes.io/release: stable
  annotations:
    a8r.io/description: "Frontpage"
    a8r.io/owner: "@faangbait"
    a8r.io/repository: "https://github.com/faangbait/windowpane"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: windowpane-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: windowpane-web
        app.kubernetes.io/part-of: windowpane
    spec:
      imagePullSecrets:
        - name: localregistry
      containers:
      - name: windowpane-web
        image: registry.lab.madeof.glass/windowpane:v1.0.0
        resources:
          limits:
            memory: 256Mi
            cpu: ".5"
---
apiVersion: v1
kind: Service
metadata:
  name: windowpane-service
  namespace: public
  labels:
    app.kubernetes.io/name: windowpane-service
    app.kubernetes.io/part-of: windowpane
spec:
  selector:
    app.kubernetes.io/name: windowpane-web
  ports:
    - port: 8080
      name: windowpane-http
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: windowpane-ingress
  namespace: public
  labels:
    app.kubernetes.io/name: windowpane-ingress
    app.kubernetes.io/part-of: windowpane
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`madeof.glass`)
      kind: Rule
      services:
        - name: windowpane-service
          port: windowpane-http
  tls:
    certResolver: letsencrypt
