cluster:
  hosts:
    node1:
      ansible_user: ss
      nic_driver: ixgbe          # Intel X520 10G 2P
      nmcli_name: enp6s0f1
      nmcli_ifname: enp6s0f1
      nmcli_gw4: "10.0.0.1"
      nmcli_ip4: "10.0.8.254/20"
    node2:
      ansible_user: ss
      nic_driver: be2net         # Emulex OneConnect 10Gb (be3)
      nmcli_name: enp3s0f1
      nmcli_ifname: enp3s0f1
      nmcli_mac: "00:90:fa:8a:03:de"
      nmcli_gw4: "10.0.0.1"
      nmcli_ip4: "10.0.8.253/20"
    node4:
      ansible_user: ss
      nic_driver: i40e          # Intel X710
      nmcli_name: enp130s0f0
      nmcli_ifname: enp130s0f0
      nmcli_mac: "68:05:ca:e5:3d:20"
      nmcli_gw4: "10.0.0.1"
      nmcli_ip4: "10.0.8.251/20"

controlplane:
  hosts:
    node1:
      ansible_user: ss
      highmem: true

workers:
  hosts:
    node2:
      ansible_user: ss
    node4:
      ansible_user: ss
      highmem: true

all:
  hosts:
    node1: {}
    node2: {}
    node4: {}
    localhost: {}
    