##### SECRETS ##################################################################
#
# kubectl config set-context --current --namespace=default
#
# read -p "DockerHub Username: " DOCKER_USER
# read -p "DockerHub Password: " DOCKER_PASS
# read -p "DockerHub Email: " DOCKER_EMAIL
#
# kubectl -n default create secret docker-registry regcred --docker-server=https://index.docker.io/v1/ --docker-username=$DOCKER_USER --docker-password=$DOCKER_PASS --docker-email=$DOCKER_EMAIL
# kubectl -n traefik create secret docker-registry regcred --docker-server=https://index.docker.io/v1/ --docker-username=$DOCKER_USER --docker-password=$DOCKER_PASS --docker-email=$DOCKER_EMAIL
# kubectl -n antennae create secret docker-registry regcred --docker-server=https://index.docker.io/v1/ --docker-username=$DOCKER_USER --docker-password=$DOCKER_PASS --docker-email=$DOCKER_EMAIL
# kubectl -n home create secret docker-registry regcred --docker-server=https://index.docker.io/v1/ --docker-username=$DOCKER_USER --docker-password=$DOCKER_PASS --docker-email=$DOCKER_EMAIL
# kubectl -n lab create secret docker-registry regcred --docker-server=https://index.docker.io/v1/ --docker-username=$DOCKER_USER --docker-password=$DOCKER_PASS --docker-email=$DOCKER_EMAIL
# kubectl -n news create secret docker-registry regcred --docker-server=https://index.docker.io/v1/ --docker-username=$DOCKER_USER --docker-password=$DOCKER_PASS --docker-email=$DOCKER_EMAIL
# kubectl -n observability create secret docker-registry regcred --docker-server=https://index.docker.io/v1/ --docker-username=$DOCKER_USER --docker-password=$DOCKER_PASS --docker-email=$DOCKER_EMAIL
# kubectl -n public create secret docker-registry regcred --docker-server=https://index.docker.io/v1/ --docker-username=$DOCKER_USER --docker-password=$DOCKER_PASS --docker-email=$DOCKER_EMAIL
# kubectl -n vault create secret docker-registry regcred --docker-server=https://index.docker.io/v1/ --docker-username=$DOCKER_USER --docker-password=$DOCKER_PASS --docker-email=$DOCKER_EMAIL
#
# export DOCKER_USER=;export DOCKER_PASS=;export DOCKER_EMAIL=
################################################################################

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-configmap
  namespace: traefik
  labels:
    app.kubernetes.io/name: traefik-configmap
    app.kubernetes.io/part-of: traefik
data:
  dynamic.yaml: |
    http:
      services:
        GitLab:
          loadBalancer:
            servers:
              - url: "http://10.0.0.254"
      routers:
        GitLab:
          entryPoints:
            - websecure
          service: GitLab
          rule: Host(`git.lab.madeof.glass`)
          tls:
            certResolver: letsencrypt
