---
# Create Grafana IngressRoute
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-ingress
  namespace: observability
  labels:
    app.kubernetes.io/name: grafana-ingress
    app.kubernetes.io/part-of: monitoring
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`mon.limitlessinteractive.com`)
      kind: Rule
      services:
        - name: kube-prometheus-stack-grafana
          port: 80
  tls:
    certResolver: letsencrypt
