
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-configmap
  namespace: traefik
  labels:
    app.kubernetes.io/name: traefik-configmap
    app.kubernetes.io/part-of: traefik
data:
  dynamic.yaml: |
    providers:
      http:
        endpoint: "http://10.0.0.254"
