# Note, this file needs to be copied to /etc/kubernetes/pki/enc.yaml
# Then, edit /etc/kubernetes/manifests/kube-apiserver.yaml to point to it
# - --encryption-provider-config=/etc/kubernetes/pki/enc.yaml
# Last, delete the kube-apiserver pod

apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
      - secrets
    providers:
      - secretbox:
          keys:
            - name: key1
              secret: REPLACEME
      - identity: {}
