apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 10.0.8.254
  bindPort: 6443
nodeRegistration:
  criSocket: "unix:///var/run/crio/crio.sock"
  imagePullPolicy: IfNotPresent
  name: node1
  taints: []
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
apiServer:
  extraArgs:
    allow-privileged: "true"
    anonymous-auth: "true" # Insecure, but nodes won't join without it...
    audit-log-maxage: "30"
    audit-log-maxbackup: "10"
    audit-log-maxsize: "100"
    audit-log-path: "/var/log/kubernetes-audit"
    authorization-mode: "Node,RBAC"
    encryption-provider-config: "/etc/kubernetes/config/secret-encryption.yaml"
    enable-admission-plugins: "DefaultStorageClass"
    feature-gates: SizeMemoryBackedVolumes=true
  extraVolumes:
    - name: config
      hostPath: "/etc/kubernetes/config"
      mountPath: "/etc/kubernetes/config"
      readOnly: true
      pathType: DirectoryOrCreate
clusterName: kubernetes
controlPlaneEndpoint: k8s-control-plane-lb
networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.96.0.0/12
  podSubnet: 10.48.0.0/16
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
ipvs:
  strictARP: true
mode: "ipvs"
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: systemd
hairpinMode: "hairpin-veth"
