##### HELM #####################################################################
#
# kubectl config set-context --current --namespace=vault
#
# helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
# helm repo update
# helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack --values=infrastructure/prometheus-values.yaml
#
##### MONITORING ##############################################################

# This config doesn't actually do anything... prometheus uses an EmptyDir
# Could make this the backing for the EmptyDir storage though.

prometheusSpec:
  volumes:
    - name: bulk-prometheus
      glusterfs:
        endpoints: glusterfs-cluster
        path: glass_bulk
  volumeMounts:
  - mountPath: /prometheus
    name: bulk-prometheus
    subPath: "prometheus/prometheus"

alertmanagerSpec:
  volumes:
    - name: bulk-alertmanager
      glusterfs:
        endpoints: glusterfs-cluster
        path: glass_bulk
  volumeMounts:
  - mountPath: /prometheus
    name: bulk-alertmanager
    subPath: "prometheus/alertmanager"
