installation:
  cni:
    type: Calico
    ipam:
      type: Calico
  calicoNetwork:
    bgp: Enabled
    ipPools:
    - cidr: 10.48.0.0/16
      encapsulation: VXLANCrossSubnet
    nodeAddressAutodetectionV4:
      cidrs:
        - "10.0.6.0/24"
