deployment:
  imagePullSecrets:
    - name: regcred
  initContainers:
    - name: volume-permissions
      image: traefik:v2.10.5
      command: ["sh", "-c", "touch /data/acme.json; chown 65532 /data/acme.json; chmod -v 600 /data/acme.json"]
      securityContext:
        runAsNonRoot: false
        runAsGroup: 0
        runAsUser: 0
      volumeMounts:
      - mountPath: /data
        name: certs

volumes:
  - name: traefik-configmap
    mountPath: "/config"
    type: configMap

logs:
  general:
    level: WARN
  access:
    enabled: true
    filePath: "/tmp/access.log"
    bufferingSize: 100

globalArguments:
  - "--global.checknewversion"

additionalArguments:
  - "--api.insecure=true"
  - "--providers.file.directory=/config"
  # TODO: https://doc.traefik.io/traefik/providers/http/

envFrom:
  - secretRef:
      name: aws-credentials

ports:
  metrics:
    port: 9999

  web:
    port: 8000
    expose: true
    redirectTo: websecure

  websecure:
    port: 8443
    expose: true
    tls:
      enabled: true
      certResolver: "letsencrypt"
      options: "default"
      domains:
        - main: "*.madeof.glass"
          sans:
            - "limitlessinteractive.com"
            - "*.limitlessinteractive.com"

    # middlewares:
    #   - vault-secure-auth@kubernetescrd # TODO: breaks prod

  dht-tcp:
    port: 51413
    expose: true
    protocol: TCP
    tls:
      enabled: true
      options: ""
      certResolver: "letsencrypt"
      domains:
        - main: "*.madeof.glass"

  dht-udp:
    port: 51414
    expose: true
    protocol: UDP

  minecraft:
    port: 25565
    expose: true
    protocol: TCP
    tls:
      enabled: true
      options: ""
      certResolver: "letsencrypt"
      domains:
        - main: "*.madeof.glass"

tlsOptions:
  default:
    sniStrict: true
    preferServerCipherSuites: true
    curvePreferences:
      - CurveP521
      - CurveP384
    minVersion: VersionTLS12

service:
  enabled: true
  type: LoadBalancer
  spec:
    loadBalancerIP: "10.0.15.129"

persistence:
  enabled: true
  storageClass: "glass-cfg"
  name: "certs"
  path: "/data"

certResolvers:
  letsencrypt:
    email: root@madeof.glass
    dnsChallenge:
      provider: route53
      delayBeforeCheck: 15
    storage: /data/acme.json

securityContext:
  capabilities:
    drop: [ALL]
  readOnlyRootFilesystem: true

nodeSelector:
  kubernetes.io/hostname: node1

podSecurityContext:
  fsGroup: 65532
  fsGroupChangePolicy: "OnRootMismatch"
  runAsGroup: 65532
  runAsNonRoot: true
  runAsUser: 65532
