- name: Apply host-specific variables
  hosts: cluster
  become: true
  any_errors_fatal: true
  tasks:
    # - name: Assert ENV Variables exist
    #   ansible.builtin.assert:
    #     that:
    #       - lookup('ansible.builtin.env', 'LOCALUSER_ACCOUNT')
    #     fail_msg: "Some required variables are not defined."
    #     success_msg: "All required variables are defined"

    - name: Set facts
      ansible.builtin.set_fact:
        localuser_account: "{{ lookup('ansible.builtin.env', 'LOCALUSER_ACCOUNT') }}"

    - name: Set derived facts
      ansible.builtin.set_fact:
        localuser_home: "/home/{{ localuser_account }}"

    - name: Configure Bare Metal Host
      ansible.builtin.import_role:
        name: configure-host

# when complete, move to 20-bootstrap-gluster.yaml
