- name: Add Calico Chart Repo
  kubernetes.core.helm_repository:
    name: projectcalico
    repo_url: https://docs.tigera.io/calico/charts

- name: "Deploy Calico {{ calico_version }}"
  kubernetes.core.helm:
    name: calico
    chart_ref: projectcalico/tigera-operator
    release_namespace: tigera-operator
    create_namespace: true
    chart_version: "{{ calico_version }}"
    values:
      installation:
        cni:
          type: Calico
        calicoNetwork:
          kubeProxyManagement: Enabled
          linuxDataplane: BPF
          bgp: Disabled
          ipPools:
            - name: default-ipv4-ippool
              blockSize: 26
              cidr: 10.48.0.0/16
              encapsulation: VXLANCrossSubnet
              natOutgoing: Enabled
              nodeSelector: all()
          nodeAddressAutodetectionV4:
            cidrs:
              - "10.0.8.0/24"
      defaultFelixConfiguration:
        enabled: true
        bpfExternalServiceMode: DSR
      kubernetesServiceEndpoint:
        host: "10.0.8.254"
        port: "6443"
